@startuml
hide footbox
skinparam actorStyle hollow
left to right direction

agent "Terminology Repository" as Server101
agent "Terminology Consumer" as Client101
agent "Terminology Repository" as Server100 
agent "Terminology Consumer" as Client100
agent "Terminology Repository" as Server99
agent "Terminology Consumer" as Client99
agent "Terminology Repository" as Server98 
agent "Terminology Consumer" as Client98
agent "Terminology Repository" as Server97 
agent "Terminology Consumer" as Client97
agent "Terminology Repository" as Server96 
agent "Terminology Consumer" as Client96
agent "Terminology Repository" as Server95 
agent "Terminology Consumer" as Client95


Server95 <-- Client95 : "Query Value Set [ITI-95]"
Server96 <-- Client96 : "Query Code System [ITI-96]"
Server97 <-- Client97 : "Expand Value Set [ITI-97]"
Server98 <-- Client98 : "Lookup Code [ITI-98]"
Server99 <-- Client99 : "Validate Code [ITI-99]"
Server100 <-- Client100 : "Query Concept Map [ITI-100]"
Server101 <-- Client101 : "Translate Code [ITI-101]"
@enduml
