@startuml
hide footbox
skinparam linetype polyline
left to right direction

agent "Terminology Repository\n\n\n\n\n\n\n" as Server 
agent "Terminology Consumer\n\n\n\n\n\n\n" as Client

Server <-- Client : "Query Value Set [ITI-95]\nQuery Code System [ITI-96]\nExpand Value Set [ITI-97]\nLookup Code [ITI-98]"
Server -[#FFFFFF]- Client: "Validate Code [ITI-99]\nQuery Concept Map [ITI-100]\nTranslate Code [ITI-101]"
@enduml

