@startuml
hide footbox


participant "Terminology Repository" as Server 
participant "Terminology Consumer" as Client

Server <-- Client : "Query Value Set [ITI-95]"
Server <-- Client : "Query Code System [ITI-96]"
Server <-- Client : "Expand Value Set [ITI-97]"
Server <-- Client : "Lookup Code [ITI-98]"
Server <-- Client : "Validate Code [ITI-99]"
Server <-- Client : "Query Concept Map [ITI-100]"
Server <-- Client : "Translate Code [ITI-101]"
@enduml

