@startuml
hide footbox

participant "Terminology Consumer" as Client
participant "Terminology Repository" as Server
activate Client
activate Server
Client -> Server : Expand Value Set Request:\nHTTP GET <Base>/ValueSet/$expand
Server -> Client : Search Value Set Response:\nValueSet
deactivate Client
deactivate Server
@enduml
