@startuml
hide footbox

participant "Terminology Repository" as Server 
participant "Terminology Consumer" as Client 

Server <- Client : "Query Value Set [ITI-95]"
Server <- Client : "Query Code System [ITI-96]"
Server <- Client : "Query Concept Map [ITI-100]"
@enduml