# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.svcm
canonical: https://profiles.ihe.net/ITI/SVCM
version: 1.5.0-current
name: IHE_ITI_SVCM
title: "Sharing Valuesets, Codes, and Maps (SVCM)"
description: "The Sharing Valuesets, Codes, and Maps (SVCM) Profile defines a lightweight interface through which healthcare systems may retrieve centrally managed uniform nomenclature and mappings between code systems based on the HL7 Fast Healthcare Interoperability Resources (FHIR) specification."
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: Trial-Implementation
#date: 2022-08-12
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+
dependencies:
  ihe.iti.balp: 1.1.0


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: 1:51. Sharing Valuesets, Codes, and Maps (SVCM)
    generation: markdown
  volume-1.md:
    title: 1:51. Sharing Valuesets, Codes, and Maps Volume 1
    generation: markdown
  ITI-95.md:
    title: 2:3.95 Query Value Set [ITI-95]
    generation: markdown
  ITI-96.md:
    title: 2:3.96 Query Code System [ITI-96]
    generation: markdown
  ITI-97.md:
    title: 2:3.97 Expand Value Set [ITI-97]
    generation: markdown
  ITI-98.md:
    title: 2:3.98 Lookup Code [ITI-98]
    generation: markdown
  ITI-99.md:
    title: 2:3.99 Validate Code [ITI-99]
    generation: markdown
  ITI-100.md:
    title: 2:3.100 Query Concept Map [ITI-100]
    generation: markdown
  ITI-101.md:
    title: 2:3.101 Translate Code [ITI-101]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Open and Closed issues
    generation: markdown
  other.md:
    title: Changes to Other Profiles
    generation: markdown
    
menu:
  SVCM Home: index.html
  Volume 1:
    "Introduction": volume-1.html
    "Actors and Transactions": volume-1.html#1511-svcm-actorstransactions
    "Actor Options": volume-1.html#1512-svcm-actor-options
    "Required Actor Groupings": volume-1.html#1513-svcm-required-actor-groupings
    "Overview": volume-1.html#1514-svcm-overview
    "Security Considerations": volume-1.html#1515-svcm-security-considerations
    "Cross-Profile Considerations": volume-1.html#1516-svcm-cross-profile-considerations
  Volume 2:
    "Query Value Set [ITI-95]": ITI-95.html
    "Query Code System [ITI-96]": ITI-96.html
    "Expand Value Set [ITI-97]": ITI-97.html
    "Lookup Code [ITI-98]": ITI-98.html
    "Validate Code [ITI-99]": ITI-99.html
    "Query Concept Map [ITI-100]": ITI-100.html
    "Translate Code [ITI-101]": ITI-101.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
  Other: other.html
